### ISSUE TITLE
Graph Convolutions

### ISSUE THREAD

**Issue by Epsilon1024** [tensorflow/graphics#10]
When using the feature_steered_convolution_layer, as part of a session, I will get the following error:

"ValueError: The initializer passed is not valid. It should be a callable with no arguments and the shape should not be provided or an instance of `tf.keras.initializers.*' and `shape` should be fully defined."

As far as I can tell, the only examples in the documentation that use this function is the mesh segmentation example.  This example, however, is using both an estimator and a pre-trained model which makes it very difficult to figure out what is going on with the initializers.  Is it possible to provide more documentation that shows exactly how to use this function, say from loading tensors into placeholders?

**Comment by julienvalentin** [comment]
The tests might make it clearer for you:
tensorflow_graphics/nn/layer/tests/graph_convolution_test.py

Let me know in case you don't manage to figure it out!

Best.

**Comment by Epsilon1024** [comment]
It works!!!  Thank you for getting back to me.  The test_feature_steered_convolution_layer_training function was most helpful to understanding how it works.  

If figured out that the problem was with the fact that the initializer needed the shape of the placeholder to be defined within the graph (not just defined by the numpy array that I feed into it).  The code that I had trouble with was something like this:

```python
data = np.array(((1.0, 1.0), (-1.0, 1.0), (-1.0, -1.0), (1.0, -1.0)))
neighbors_indices = np.array(((0, 0), (0, 1), (0, 3),
                              (1, 0), (1, 1), (1, 2),
                              (2, 1), (2, 2), (2, 3),
                              (3, 0), (3, 2), (3, 3)),dtype=np.int64)
labels = np.reshape([-1.0, -0.5, 0.5, 1.0], (-1, 1))
Indices = neighbors_indices
Values = np.ones(shape=(12,),dtype=np.float64) / 3.0
Shape = np.array([4,4],dtype=np.int64)
V0 = tf.placeholder(dtype=tf.float64,name="V0")
adj_sp = tf.sparse_placeholder(dtype=tf.float64,name='SP')
output = graph_conv.feature_steered_convolution_layer(data=V0,neighbors=adj_sp,sizes=None,translation_invariant=False,num_weight_matrices=1,num_output_channels=1)
sess = tf.Session()
sess.run(tf.global_variables_initializer())
a = sess.run(output,feed_dict={V0:data,adj_sp:(Indices,Values,Shape)})
print(a)
```
Once I added in the shapes, it worked fine.  One part that was a bit unintuitive, however, was if you want to have a sparse placeholder for the adjacency matrix, the feed dictionary must pass a tuple containing (indices,values,shape).  The placeholder shape, must be the same size as the indices array, not the dense array shape.  (This was not obvious because placeholders don't normally need their shapes defined beforehand.  The working code is shown below:

```python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
import os
import tensorflow as tf
from tensorflow_graphics.notebooks import mesh_segmentation_dataio as dataio
from tensorflow_graphics.nn.layer import graph_convolution as graph_conv
import json
import numpy as np

data = np.array(((1.0, 1.0), (-1.0, 1.0), (-1.0, -1.0), (1.0, -1.0)))
neighbors_indices = np.array(((0, 0), (0, 1), (0, 3),
                              (1, 0), (1, 1), (1, 2),
                              (2, 1), (2, 2), (2, 3),
                              (3, 0), (3, 2), (3, 3)),dtype=np.int64)
labels = np.reshape([-1.0, -0.5, 0.5, 1.0], (-1, 1))

Indices = neighbors_indices
Values = np.ones(shape=(12,),dtype=np.float64) / 3.0
Shape = np.array([4,4],dtype=np.int64)

V0 = tf.placeholder(dtype=tf.float64,name="V0",shape=(None,2))
adj_sp = tf.sparse_placeholder(shape=(None,2),dtype=tf.float64,name='SP')

output = graph_conv.feature_steered_convolution_layer(data=V0,neighbors=adj_sp,sizes=None,translation_invariant=False,num_weight_matrices=1,num_output_channels=1)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
a = sess.run(output,feed_dict={V0:data,adj_sp:(Indices,Values,Shape)})
print(a)
```

**Comment by julienvalentin** [comment]
Awesome! I let you close the issue if you are all set.

Best.

**Comment by Epsilon1024** [comment]
I have one more related question:

In the example in the test file, the adjacency matrix is of rank 2.  In the mesh segmentation demo, the adjacency matrix is of rank 3.  According to the documentation in the mesh segmentation demo, it should be of shape (B,V,V) (see below):
```
  """A mesh encoder using feature steered graph convolutions.

    The shorthands used below are
      `B`: Batch size.
      `V`: The maximum number of vertices over all meshes in the batch.
      `D`: The number of dimensions of input vertex features, D=3 if vertex
        positions are used as features.

  Args:
    batch_mesh_data: A mesh_data dict with following keys
      'vertices': A [B, V, D] `float32` tensor of vertex features, possibly
        0-padded.
      'neighbors': A [B, V, V] `float32` sparse tensor of edge weights.
      'num_vertices': A [B] `int32` tensor of number of vertices per mesh.
    num_filters: The number of weight matrices to be used in feature steered
      graph conv.
    output_dim: A dimension of output per vertex features.
    conv_layer_dims: A list of dimensions used in graph convolution layers.

  Returns:
    vertex_features: A [B, V, output_dim] `float32` tensor of per vertex
      features.
  """
```

When I create a similar type of adjacency matrix, however, based off of the code I posed in my previous comment (except with my own data set with several meshes and a (B,V,V) adjacency matrix), I get the following error:

`ValueError: neighbors must have a rank of 2, but it has rank 3 and shape [None, None, None]`
