### ISSUE TITLE
Street view as input

### ISSUE THREAD

**Issue by ShettyHarapanahalli** [tensorflow/graphics#112]
Just wondering, if we feed streetview images for this what can be expected results ...

**Comment by julienvalentin** [comment]
This question is too broad. Please describe what the intended tasks are.

**Comment by ShettyHarapanahalli** [comment]
let me put it 2 phases if a 360 deg images of a room is shared for this model will I be able to localize the camera from a different position, usage of this for AR or mixed reality can get better results.  putting this on street view/maps will be able to generate 3D map of the street, get a better understanding of surroundings for autonomous vehicles and help localize them with just visual information. Can the model consider reflections, shadows etc to understand the environment better ( in bends and other corner cases).

**Comment by julienvalentin** [comment]
I would suggest that you to define the technical bits you need to realize what you have in mind and browse the documentation. A couple of things you describe can indeed be done.
