### ISSUE TITLE
Issue creating my own dataset before training

### ISSUE THREAD

**Issue by ankitpatnala** [tensorflow/graphics#113]
I see that in mesh_segmenetation_demo.py we use tfrecordfiles for training.
in the example i am getting it directly from keras dataset but i want to create something from .obj files. How can i convert my obj files to tfrecords file.
as i see the feature is 'labels' : _byte_feature
'num_vertices' : _int_feature
'num_traingles; : _int_feature
'vertices'  : _byte_feature
'traingles' : _byte_feature

i am unable to understand this _byte_feature. How they are written in the tfrecord file

**Comment by avneesh-sud** [comment]
Hi ankitpatnala,

This seems a dup of issue #14 (https://github.com/tensorflow/graphics/issues/14). PTAL at the suggestions there, and let us know if that resolves your question.

**Comment by ankitpatnala** [comment]
I somehow found that but I have another issue. During training do we need to assign each vertex a label. What if number of vertex for each mesh is different ? Will it be possible to train ?

**Comment by ankitpatnala** [comment]
<ipython-input-13-a5dc8fe3ad60> in <module>()
      9 with input_graph.as_default():
     10   mesh_load_op = dataio.create_input_from_dataset(
---> 11       dataio.create_dataset_from_tfrecords, record_file_test, test_io_params)
     12   with tf.Session() as sess:
     13     test_mesh_data, test_labels = sess.run(mesh_load_op)

3 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_graphics/notebooks/mesh_segmentation_dataio.py in create_input_from_dataset(dataset_fn, files, io_params)
    329                                                 mesh_data['edge_weights'],
    330                                                 mesh_data['num_edges'],
--> 331                                                 mesh_data['num_vertices'])
    332 
    333   max_num_verts = tf.reduce_max(input_tensor=mesh_data['num_vertices'])

/usr/local/lib/python3.6/dist-packages/tensorflow_graphics/notebooks/mesh_segmentation_dataio.py in adjacency_from_edges(edges, weights, num_edges, num_vertices)
     79       tensors=(edges, weights, num_edges, num_vertices),
     80       tensor_names=('edges', 'weights', 'num_edges', 'num_vertices'),
---> 81       axes=(-3, -2, -1, -1))
     82   shape.compare_dimensions(
     83       tensors=(edges, weights),

/usr/local/lib/python3.6/dist-packages/tensorflow_graphics/util/shape.py in compare_dimensions(tensors, axes, tensor_names)
    372     dimensions = [
    373         int(tensor.shape[axis]) if tensor.shape[axis].value is not None else 1
--> 374         for tensor, axis in zip(tensors, axes)
    375     ]
    376   else:

/usr/local/lib/python3.6/dist-packages/tensorflow_graphics/util/shape.py in <listcomp>(.0)
    372     dimensions = [
    373         int(tensor.shape[axis]) if tensor.shape[axis].value is not None else 1
--> 374         for tensor, axis in zip(tensors, axes)
    375     ]
    376   else:

AttributeError: 'NoneType' object has no attribute 'value'



"Any solution to this ?" i am not sure whether i encoded my mesh data into the tfrecords format properly. Can you give some information about it ?

current implementation that i am doing is 

record_file_test = 'mesh.tfrecords'
record_file_eval = 'mesh2.tfecords'

def _bytes_feature(value):
  """Returns a bytes_list from a string / byte."""
  if isinstance(value, type(tf.constant(0))):
    value = value.numpy() # BytesList won't unpack a string from an EagerTensor.
  return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))

def _float_feature(value):
  """Returns a float_list from a float / double."""
  return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))

def _int64_feature(value):
  """Returns an int64_list from a bool / enum / int / uint."""
  return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))

def _tensor_feature(values, dtype):
    values = tf.dtypes.cast(values, dtype)
    serialised_values = tf.io.serialize_tensor(values)
    return tf.train.Feature(
        bytes_list=tf.train.BytesList(value=[serialised_values.numpy()]))
        
def mesh_of_tensor_train_example(idx_of_stl_files):
  feature = {
      'labels' : _tensor_feature(training_mesh_list_new[idx_of_stl_files]['labels'],tf.int32),
      'num_triangles' : _int64_feature(len(training_mesh_list_new[idx_of_stl_files]['triangles'])),
      'num_vertices' : _int64_feature(len(training_mesh_list_new[idx_of_stl_files]['vertices'])),
      'triangles'  : _tensor_feature(training_mesh_list_new[idx_of_stl_files]['triangles'],tf.int32),
      'vertices'   : _tensor_feature(training_mesh_list_new[idx_of_stl_files]['vertices'],tf.float32),
  }
  return tf.train.Example(features = tf.train.Features(feature = feature))

with tf.io.TFRecordWriter(record_file_test) as writer:
  for idx_of_stl_files in range(0,len(training_mesh_list_new)-10):
    tf_record_data = mesh_of_tensor_train_example(idx_of_stl_files)
    writer.write(tf_record_data.SerializeToString())

with tf.io.TFRecordWriter(record_file_eval) as writer:
  for idx_of_stl_files in range(len(training_mesh_list_new)-10,len(training_mesh_list_new)):
    tf_record_data = mesh_of_tensor_train_example(idx_of_stl_files)
    writer.write(tf_record_data.SerializeToString())

**Comment by ankitpatnala** [comment]
No worries. I found the problem . I was using tf2 which i sin eagerly mode and it couldn't recogninze the syntax . setting the early_execution to false serves my purpose

**Comment by julienvalentin** [comment]
Glad that you resolved this!
Closing
