### ISSUE TITLE
Render too slow on GPU

### ISSUE THREAD

**Issue by liuppboy** [tensorflow/graphics#123]
I use the [rasterizer](https://github.com/tensorflow/graphics/blob/master/tensorflow_graphics/rendering/rasterizer.py) for rendering 3D vertices to 2D image, but it turns to be rather slow on gpu (even much slower than on cpu). Can it run faster? Thanks!

**Comment by julienvalentin** [comment]
Hi @liuppboy,

The current version of the rasterizer in pure TF / python is getting reworked by @cem-keskin as we speak. If you need something fast on GPU, I invite you to check the OpenGL Rasterizer. The final PR (batching) is currently in review.

Best.

**Comment by julienvalentin** [comment]
Closing .
