### ISSUE TITLE
AttributeError caused by tensor.shape[axis].value in shape.py compare_dimensions

### ISSUE THREAD

**Issue by oracle3001** [tensorflow/graphics#124]
When using Tensorflow 2.0 nightly, if I use the spherical_harmonics.evaluate_spherical_harmonics in a custom layer, I get the following error.

```
...tensorflow_graphics\util\shape.py:369 compare_dimensions  *
        dimensions = [

    AttributeError: 'int' object has no attribute 'value'
```

caused by 

`int(tensor.shape[axis]) if tensor.shape[axis].value is not None else 1`

**Comment by julienvalentin** [comment]
Hi!

Could you create a minimal example reproducing the error on https://colab.research.google.com/?

Best.

**Comment by cem-keskin** [comment]
Please make sure you are using the latest version of tf_graphics, as this
problem should have been solved a while ago.

**Comment by oracle3001** [comment]
AFAIK, I am using the latest version from Git. There appears to be an outstanding pull request on this issue,

https://github.com/tensorflow/graphics/pull/109

**Comment by cem-keskin** [comment]
OK, working on a fix now, thanks.
Just to clarify, do you disable eager execution, or do you use tf.function
decorator?

**Comment by julienvalentin** [comment]
@oracle3001 and @cem-keskin is this resolved?

**Comment by cem-keskin** [comment]
Yes this should have been fixed about 3 weeks ago.
