### ISSUE TITLE
Request: Example for how to use ray.triangulate

### ISSUE THREAD

**Issue by oveddan** [tensorflow/graphics#125]
This repository is awesome and I can't wait to see what comes out of it.  I'm glad there seems to be a tensorflow based version of triangulation.

It would be great if there was an example of how to use the `ray.triangulate` method.

A common use case is you have multiple cameras with known intrinsic and extrinsic parameters, and the same points visible from each camera, how can you triangulate those points?

[OpenCV's sfm triangulate](https://docs.opencv.org/3.4/d0/dbd/group__triangulation.html) module allows you to pass in a projection matrix from each camera, and the 2d point correspondences.  This is pretty easy to consume.

In the tensorflow graphics [tfg.geometry.representation.ray.triangulate](https://www.tensorflow.org/graphics/api_docs/python/tfg/geometry/representation/ray/triangulate) requires using rays for triangulate.   it would be nice if there was an end to end example showing:
1. How can you compute the rays given known camera parameters and 2d points.
2. How do you build the weights tensor

**Comment by julienvalentin** [comment]
Hi @oveddan ,

A couple of pointers:
1. we have a few camera models in rendering/camera. These models are equipped with a ray method that does what you are after
2. I believe that https://www.tensorflow.org/api_docs/python/tf/meshgrid would be a good choice 

We are always after contributions from the community, so if you are interested to write a short tutorial in the form of a Colab on the problem you describe, it would be awesome to make it available to the TensorFlow Graphics community. Let us know!

Best.

**Comment by oveddan** [comment]
Thanks for the pointers @julienvalentin 

Good to see that the `camera` functions have methods to unproject rays.
That being said, it doesn't seem like they take a model view transformation parameter, which is necessary for my case.

In my case, I'm using opencv calibration results from multiple real world cameras, and 2d corresponding points, to triangulate to 3d.  I got something working using code from [Soccer on Your Tabletop](https://github.com/krematas/soccerontable):

In that repository, in [camera.py](https://github.com/krematas/soccerontable/blob/master/utils/camera.py#L257), there is a function `unproject` which takes into consideration the camera transformation and rotation.

So I call `unproject` with the camera intrinsic and extrinsic parameters set, and set the depth to 0.5.
This becomes the ray `end_point`
The ray `start_point` is the camera position, which is retreived by calling [get_position](https://github.com/krematas/soccerontable/blob/master/utils/camera.py#L270) on a camera instance

So this gives me enough to use tf.graphics `triangulate` - which I have working successfully now.

When the project is in a good state, I will hope to open source the use case in a colab notebook!

Is there a way, if any, for tf.graphics `camera` functions to account for model view to camera transformations?

**Comment by julienvalentin** [comment]
Hi @oveddan ,

If you need to transform points from world to camera coordinates, you can use any transformations in tensorflow_graphics.geometry.transformation for this purpose.

Best.

**Comment by nmerrill67** [comment]
Here is a brief example I wrote to test how this is supposed to work. I assign a feature at [1 2 3], project it into two fake image planes, then back again with a depth of 1 for the ray end points. Then I triangulate and make sure the triangulated point is close to [1 2 3] and that the gradient exists. This is tested with tf 2.4
```
import numpy as np
import tensorflow as tf
import tensorflow_graphics
import tensorflow_graphics.geometry
import tensorflow_graphics.geometry.representation as tfgrep

def euler2R(euler):
    # Assume euler = {gamma, beta, alpha} (degrees)
    g, b, a = np.deg2rad(euler).astype(np.float64)
    """
    Rx = np.array([[1, 0, 0],
                    [0, cos(r), -sin(r)],
                    [0, sin(r), cos(r)]], dtype=np.float64)
    Ry = np.array([[cos(p), 0, sin(p)],
                    [0, 1, 0],
                    [-sin(p), 0, cos(p)]], dtype=np.float64)
    Rz = np.array([[cos(y), -sin(y), 0],
                  [sin(y), cos(y), 0],
                  [0, 0, 1]], dtype=np.float64)
    R = np.matmul( np.matmul(Rz, Ry), Rx )
    """
    cosa = np.cos(a)
    cosb = np.cos(b)
    cosg = np.cos(g)
    sina = np.sin(a)
    sinb = np.sin(b)
    sing = np.sin(g)
    R = np.array([[cosa*cosb, cosa*sinb*sing - sina*cosg, cosa*sinb*cosg + sina*sing],
                  [sina*cosb, sina*sinb*sing + cosa*cosg, sina*sinb*cosg - cosa*sing],
                  [-sinb, cosb*sing, cosb*cosg]], dtype=np.float64)

    return R

# Feature in global frame
p = np.array([1.,2.,3.])[:,None]

# Fake camera matrix
K = np.array([[112., 0., 112.],
              [0., 112., 112.],
              [0.,   0.,   1.]])
Kinv = np.linalg.inv(K)

# Camera pose 1 in G
T1toG = np.eye(4)
ray_start1 = T1toG[:3,3:4]
p_inI1 = K @ p

# Ray endpoint from camera center with depth 1
ray_end1 = Kinv @ p_inI1 / p_inI1[2]

# pose 2 in G with sufficient parallax
T2toG = np.eye(4)
T2toG[:3,:3] = euler2R(np.array([0,0,30]))
T2toG[:3,3] = np.array([[0,-1,0]])
ray_start2 = T2toG[:3,3:4]
TGto2 = np.linalg.inv(T2toG)

p_in2 = TGto2[:3,:3] @ p + TGto2[:3,3:4]
p_inI2 = K @ p_in2
ray_end2 = T2toG[:3,:3] @ Kinv @ p_inI2 / p_inI2[2] + T2toG[:3,3:4]

ray_start = np.squeeze(np.stack([ray_start1, ray_start2]))
ray_end = np.squeeze(np.stack([ray_end1, ray_end2]))
ray_start = tf.convert_to_tensor(ray_start, dtype=tf.float32)
ray_end = tf.convert_to_tensor(ray_end, dtype=tf.float32)

with tf.GradientTape() as g:
    g.watch(ray_end)
    p_est = tfgrep.ray.triangulate(ray_start, ray_end, tf.ones((2)))
    print("Original pt:", p.T)
    print("Triangulated pt:", p_est)
    print("Grad from ray_end:", g.gradient(p_est, ray_end))

```
