### ISSUE TITLE
Request: camera distortion for camera project api

### ISSUE THREAD

**Issue by dong100136** [tensorflow/graphics#128]
hello, when i use this library, i find it's camera project api which project 3d points into camera pane,  only take care of fx,fy, but not including  distortion. 

tfg.rendering.camera.perspective.project

**Comment by julienvalentin** [comment]
Hi @dong100136 

In case you did not notice it, the camera module comes with radial distortion: tensorflow_graphics/rendering/camera/quadratic_radial_distortion.py

Best.

**Comment by dong100136** [comment]
Thanks for reminding, this api helps me a lot. 
The doc didn't mention it, should we update the doc?
