### ISSUE TITLE
Is it possible to get "certainty/weights" as a result of triangulate?

### ISSUE THREAD

**Issue by oveddan** [tensorflow/graphics#129]
The [triangulate](https://www.tensorflow.org/graphics/api_docs/python/tfg/geometry/representation/ray/triangulate) function takes as a parameter a tensor of weights/certainties.

How can you determine the certainty of the output triangulated points?  Would it be possible to append weights to the tensor that is returned?

**Comment by anastasia-tkach** [comment]
The implemented triangulation algorithm does not output certainties of the triangulated points.

**Comment by julienvalentin** [comment]
Thanks for your swift answer @anastasia-tkach !

@oveddan this should be a relatively simple extension; would you be interested in implementing that?

**Comment by oveddan** [comment]
I'd be glad to do it!  Could you please explain how the algorithm would be extended to support this?

**Comment by julienvalentin** [comment]
@anastasia-tkach please let @oveddan know when you get a chance!

**Comment by fulkast** [comment]
Hi @julienvalentin @oveddan! 
I was interested in solving this problem as well. However, after reading the algorithm I realised that the `weights` in the current interface only facilitates the solving of the weighted least squares problem. It allows rays with higher weights to have more influence on the resultant points. 

To derive uncertainty of the result points one would need to propagate information about the uncertainty of the input rays, the scalar weights themselves aren't a measure of uncertainty.

That said, one could still look at the residual of the weighted least square problem as a measure of trustworthiness of the solution point. In this case, the residual would provide the weighted average shortest distance between the solution point and the rays. In the ideal case, when the input data has a perfect intersection point this residual would be zero.

**Comment by julienvalentin** [comment]
@fulkast indeed the distance from the points to the computed solution is a good measure

**Comment by fulkast** [comment]
@julienvalentin that sounds good!

Naturally, the bulk of the set up of the algorithm would be identical to the `triangulate` function. For a first pass, would you recommend just duplicating the code before refactoring out the commonalities?

**Comment by julienvalentin** [comment]
@fulkast yes let's do that

**Comment by fulkast** [comment]
Hi @julienvalentin, @oveddan 

I've found that there already exists a `distance_to_ray` function in the `point` module. In the interest of maintainability perhaps it would be better to use that instead?

In that case, the following snippet calculates the weighted average distance from the triangulated points to the rays:

```python
import tensorflow as tf
from tensorflow_graphics.geometry.representation.point import distance_to_ray
from tensorflow_graphics.geometry.representation.ray import triangulate

import numpy as np

# ... initialize startpoints, endpoints and weights

intersection_points = triangulate(startpoints, endpoints, weights)
# the distance_to_ray API assumes one point for each distance to ray calculated
tf.tile(tf.expand_dims(intersection_points, axis=-2), (1,1,startpoints.shape[-2],1) ) # expand and tile to get one point for each ray
dists = distance_to_ray(intersection_points, startpoints, (tf.nn.l2_normalize(endpoints - startpoints, axis=-1)) # API uses points, startpoints, normalized direction convention
weighted_average_distance = tf.reduce_mean(tf.squeeze(dists, axis=-1) * weights, axis=-1) / tf.reduce_sum(weights, axis=-1)

with tf.Session() as sess:
    sess.run(weighted_average_distance)
```

In accordance with the documentation for `triangulate` the snippet above yields a tensor of shape
`[A1, ..., An]` where each entry holds the weighted average distance (determined by `weights`) from the calculated triangulated point to the `V` rays defined by `startpoints` and `endpoints`. In the ideal case, all the rays in one block (of the `[A1, ... An]`) intersect and the `weighted_average_distance` for that entry should be zero, or very close. However, when the different rays don't actually intersect at a common point (which is highly likely in 3 dimensions), the distance would be something larger.

Let me know if this works for your use case.

**Comment by julienvalentin** [comment]
Let us know @oveddan!

**Comment by julienvalentin** [comment]
Closing as this has been idle for a while.
