### ISSUE TITLE
import time too long

### ISSUE THREAD

**Issue by MaximeLemonnier-Leddartech** [tensorflow/graphics#131]
using latest pypi version
https://files.pythonhosted.org/packages/d1/5d/b84b85322723aef25e5069596438a92dc7d5d1035ee11947e2105315eaa2/tensorflow_graphics-1.0.0-py2.py3-none-any.whl (243kB)

executing 
`import tensorflow_graphics`

... takes over 35 sec to run, is that normal?

Thanks for the great library, anyways!
you guys rock!

**Comment by julienvalentin** [comment]
Hi @MaximeLemonnier-Leddartech 

Can you mention how long importing tensorflow is on your system?

Best.

**Comment by MaximeLemonnier-Leddartech** [comment]
Hi, it takes 4 seconds (cpu).

On another machine (with GPU), 
tensorflow takes 3 sec
tensorflow_graphics takes 15 secs (just noticed, much better, but still a tad long in some debugging scenario)
Thanks!

**Comment by MaximeLemonnier-Leddartech** [comment]
btw, I'm currently ignoring these warnings
`Warning: To use the exr data format, please install the OpenEXR package following the instructions detailed in the README at github.com/tensorflow/graphics.
Warning: To use the threejs_vizualization, please install the colabtools package following the instructions detailed in the README at github.com/tensorflow/graphics.`

Also, after a reboot, import tensorflow_graphics is down to 20secs on the CPU-only machine, so it seems related to system state.

What is considered normal load time?

**Comment by julienvalentin** [comment]
Hi @MaximeLemonnier-Leddartech 

Sorry for the late reply; I am able to replicate and will look into it for the next release.

Best.

**Comment by ataiya** [comment]
Until this is fixed, if you are a contributor, you can remove most of the `from tensorflow_graphisc.* import*` from the `__init__.py` files. I removed these from 
```
tensorflow_graphics/__init__.py
tensorflow_graphics/nn/__init__.py
tensorflow_graphics/util/__init__.py
```

And `import tensorflow_graphics.nn.layer` went from 30s import time to 1s.

And if you are a contributor, you can avoid these to be picked up by a commit with:
```
git update-index --assume-unchanged graphics/tensorflow_graphics/__init__.py
git update-index --assume-unchanged graphics/tensorflow_graphics/nn/__init__.py
git update-index --assume-unchanged graphics/tensorflow_graphics/util/__init__.py
```

This is just a temporary hack, while we work in addressing it properly

**Comment by ataiya** [comment]
Alright, the speedup update is rolled out, please take a look, and re-open if you have any problem/question.
