### ISSUE TITLE
Add Roadmap.md

### ISSUE THREAD

**Issue by bhack** [tensorflow/graphics#132]
Is there a roadmap for this TF subprojects.
Seems that It Is very low resource so It Is interesting if you can share TF plans/expectation on this.

**Comment by julienvalentin** [comment]
Hi @bhack 

Thanks for your question!
We will release 1.1 around the end of the year / early next year, packing a flexible and fast renderer leveraging OpenGL + new tutorials. I am also hoping to see more and more contributions from the community, especially in terms of state of the art models.

After 1.1, we will transition to a much more community-lead, both in terms of directions and implementation/development. We are currently looking into setting up a SIG: https://github.com/tensorflow/community/blob/master/governance/SIGS.md

Do you have specific ideas or directions you believe would be cool for TF Graphics to pursue? 

Best.

**Comment by bhack** [comment]
Anything specific but users/devs just want generally want to have an outlook on tools to adopt, expecially for subprojects in early stages like this one. 
Other libs are published like https://github.com/NVIDIAGameWorks/kaolin.
So I think that It Is useful to give a Roadmap perspective and if It Is a single Dev project or if TF can build up  enough momentum/resource on this.

**Comment by bhack** [comment]
One of the interesting topics could be to analyze what Is missing about a differntiable slam like [gradSLAM](http://montrealrobotics.ca/gradSLAM/).
Code will be release mid Jan 2020 but is pytorch based.

**Comment by julienvalentin** [comment]
I am currently working on setting up a Special Interest Group, which will make this library much more community lead, both in terms of directions and contributions.

The current overarching themes I had in mind are differentiable 3D (SLAM is part of this), Graphics, and neural rendering in order to have useful tools for the community to efficiently advance their research and make the outcome of their work as much plug-and-play as possible for future work to build on top etc.

I am at the initial phase of identifying people who would be interested, if you happen to be interested, please send me an email julienvalentin@google.com!

I just had a look at gradSLAM. and it looks super cool. I will contact the authors and see if they would be interested in joining forces.

Best.

**Comment by bhack** [comment]
If you want you could try to get in contact with speakers and organizers at http://www.visualslam.ai

**Comment by bhack** [comment]
Another interesting topic to evaluate "Geometric Capsule Autoencoders for 3D Point Clouds":

https://arxiv.org/abs/1912.03310

**Comment by tetterl** [comment]
@julienvalentin any estimation when 1.1 will be released? Will it have the ability to render textures (including backpropagation) to learn/train textures?

**Comment by bhack** [comment]
I think a Roadmap It Is more interesting now that there Is another player: https://ai.facebook.com/blog/-introducing-pytorch3d-an-open-source-library-for-3d-deep-learning/

**Comment by julienvalentin** [comment]
Hi @tetterl  and @bhack 

I will work on a Roadmap, but would like to give you a heads-up about some directions:
- finish packaging the differentiable rasterizer [teaser WIP demo: https://storage.googleapis.com/tensorflow-graphics/communication/misc_github/face_fitting.gif]
- kick-start the Special Interest Group with the founding members. I will be finalizing the list of founding members soon. The first step of this SIG is going to be to define workstreams and to increase the structure around this effort. The main themes are going to be along the lines of differentiable rendering, neural rendering, pre/post processing tools, and network implementations. See more details in the current proposal here: https://docs.google.com/document/d/1RBnBuTb0eZropAeawwQKNwqE94mtp7InAvM2y_hitIk/edit?usp=sharing 
- there will be a folders model for people to contribute their publication / research into; details TBD but likely going to be in the form of submodules.

Finally, I would love to better understand how to better engage with the community / contributors on Github; I unfortunately did not get the chance to investigate much in this direction & tools available. Any feedback is more that welcome on this front.

I hope this answers some of your questions!

Best.

**Comment by bhack** [comment]
Gradslam will be released on April https://github.com/montrealrobotics/gradSLAM

**Comment by osanseviero** [comment]
Hi @bhack. We've added our roadmap in https://github.com/tensorflow/graphics/issues/340. Please take a look, it would be great to hear your opinion!
