### ISSUE TITLE
Segmentation of dataset

### ISSUE THREAD

**Issue by etnikg** [tensorflow/graphics#134]
HI,
I want to train the model with the same dataset but with different segmentation(e.g. to train for detecting only legs and the rest). Is there any tool to done that or I have to associate manually for each vertex- a label (and if this is, how can I do that)?

**Comment by avneesh-sud** [comment]
You should be able to generate a new labeling by creating a map from existing label ids to desired part labels. See the image at top of the demo notebook mesh_segmentation_demo.ipynb for existing part definitions. For eg if you want a binary label {legs vs rest}, you can map {head, chest, abdomen, pelvis, *arm, *hand} -> 0, and {*leg, *foot} -> 1.
