### ISSUE TITLE
a problem in shape.py

### ISSUE THREAD

**Issue by LeemeetElaine** [tensorflow/graphics#143]
when I use the API tfg.geometry.representation.grid.generate, there is an error

`AttributeError: in converted code:

    tfg_geometry_grid_gen.py:31 call  *
        tensor_grid = tfg.geometry.representation.grid.generate((0,0),(shape[1]-1,shape[2]-1),(shape[1],shape[2]))
    /home/kunb/Installed/anaconda3/lib/python3.7/site-packages/tensorflow_graphics/geometry/representation/grid.py:118 generate  *
        shape.compare_dimensions((starts, stops, nums), -1,
    /home/kunb/Installed/anaconda3/lib/python3.7/site-packages/tensorflow_graphics/util/shape.py:372 compare_dimensions  *
        dimensions = [

    AttributeError: 'int' object has no attribute 'value'`
 then I delete the attribute 'value' in shape.py:374 and repair that, what's more, maybe it's better to declare the dtype of tensor starts\stops\nums in grid.py:101

**Comment by fulkast** [comment]
Hi @LeemeetElaine,

It appears the line you mentioned (`shape.py:374`) has changed since commit f41134d. The `value` attribute no longer exists on the line you mentioned. Have you tried running your code with the latest revision of the code?

**Comment by LeemeetElaine** [comment]
thanks a lot, I installed tfg by pip ,so maybe it's not the latest version
