### ISSUE TITLE
Incorrect quaternion result with between_two_vectors_3d

### ISSUE THREAD

**Issue by ecpoppenheimer** [tensorflow/graphics#152]
When I use quaternion.between_two_vectors_3d, to generate a quaternion to from +x-axis to -x-axis (180 degree rotation, going from (1, 0, 0) to (-1, 0, 0)) the result is incorrect: a tensor of zeros.  If I instead go from (1, 0, 0) to (-.999, .001, 1), the result is correct.

Also, the function doesn't work correctly with a tf.function decorator, which is annoying but tolerable.  Other people have had this problem.

Also, loading the tensorflow_graphics module seems to take an unreasonably long time.  Much longer than to load tensorflow.

`
import tensorflow as tf
from tensorflow_graphics.geometry.transformation.quaternion import between_two_vectors_3d

a = tf.constant((1, 0, 0), dtype=tf.float64)
b = tf.constant((0, 1, 0), dtype=tf.float64)
c = tf.constant((-.999, .001, 0), dtype=tf.float64)
d = tf.constant((-1, 0, 0), dtype=tf.float64)

print("no rotation:")
print(between_two_vectors_3d(a, a))
print("90 deg rotation between x and y axis: ")
print(between_two_vectors_3d(a, b))
print("almost 180 degree rotation from x-axis to negative x-axis:")
print(between_two_vectors_3d(a, c))
print("180 degree rotation from x-axis to negative x-axis: BROKEN")
print(between_two_vectors_3d(a, d))

@tf.function
def f(a, b):
    return between_two_vectors_3d(a, b)
    
print(f(a, b))
`

**Comment by fulkast** [comment]
I like how the current implementation uses the half angle formula and the normalisation to achieve the correct quaternion.

I've been giving the problem some thought. While it seems rather straightforward to fix the problem by adding a specialisation (using an if statement) for the degenerate case where the vectors are anti-parallel, I can't wrap my head around obtaining continuous derivatives for this case. When the two vectors are anti-parallel, any unit vector on the plane orthogonal to these two vectors can be used for the imaginary component of the quaternion. But different tiny perturbations to any of the two vectors could lead to drastically different resultant quaternions.

@podlipensky what's your take on this?

Best,
Frank

**Comment by ecpoppenheimer** [comment]
A continuous derivative might be necessary for some users who care about the quaternion itself, but I would imagine that most users are going to simply use the quaternion to rotate something, and the rotation should still be totally continuous, right?  My intuition is that discontinuities from the quaternion will cancel out during the rotation, and so the gradient of the whole process should be fine.  And actually, my application is full of little discontinuities, and yet it still permits optimization.  I am building a differentiable ray tracer that can be used to optimize optical systems; every time a ray jumps from interacting with one geometry element to another, there is a discontinuity in the output (a discontinuity in the forward pass, not just the gradient), yet despite that it still works pretty well.

**Comment by fulkast** [comment]
Hi @ecpoppenheimer 
1cb9eb from @podlipensky should have fixed the issue you mentioned above wrt incorrect question result. May you give this a try on your setup locally?

**Comment by shariq-audiofocus** [comment]
Thanks for fixing this, tfgraphics is pretty cool!

This issue is fixed when I install via `pip install tensorflow-graphics` but still exists when I install the GPU version `pip install --upgrade tensorflow-graphics-gpu` is that expected?

I would like to utilize my GPU, is there a way to install the gpu version with this fix?

**Comment by podlipensky** [comment]
I believe`tensorflow-graphics-gpu` is deprecated. Is there a reason why you use that old version? Current `tensorflow-graphics` should work on GPU just fine.

**Comment by shariq-audiofocus** [comment]
@podlipensky ok, yeah I think `tensorflow-graphics` is using the GPU on my workload. Nowhere in the documentation does it say `tensorflow-graphics-gpu` is deprecated though. Added it to this other issue I raised about documentation: https://github.com/tensorflow/graphics/issues/535
