### ISSUE TITLE
Improved/updated installation instructions for new rendering functions

### ISSUE THREAD

**Issue by michele-arrival** [tensorflow/graphics#153]
As a potential user of bleeding-edge features like the opengl renderer it would be usefult to have some instructions updated to show how to install the package.

In other words, I would like to test the opengl renderer and i haven't found a way to install the tensorflow-graphics package in my python environment that includes the gen_rasterizer_op native funcitons. I can build them but i have no idea how to install the libraries as part of the package.

Congrats for the amazing progress indeed!

**Comment by julienvalentin** [comment]
Hi Michele,

Thanks for reaching out and your interest!
We are currently battling with some packaging problems involving the
rasterizer, but we are hoping to come to a conclusion soon.

Best.

**Comment by julienvalentin** [comment]
@michele-arrival I am closing this for now as this is a working item. We are making good progress so hoping to resolve this shortly.

**Comment by michele-arrival** [comment]
thanks for the updates!
