### ISSUE TITLE
Contribution Guidelines

### ISSUE THREAD

**Issue by kv3n** [tensorflow/graphics#16]
Hi, I had a need to draw Lines in my 3D viewer, so I wrote a simple _triangular_mesh_plus_line_renderer_ function within the _threejs_visualization.py_ file. I am curious to know if there is a contribution guideline specific to this repository and if there are any testing procedures prior to doing a pull request? Or should I just open a feature request and have someone look at it eventually?

The major change is this private helper function that is called from _triangular_mesh_plus_line_renderer_.

```
def _vertices_to_line_geometry_material(line):
  """Converts a series of vertices to a Three.js BufferGeometry object and
     a line material that can be used to render lines.

  Args:
    vertices: a [V,3] numpy ndarray containing the position of the vertices
      composing the mesh. V denotes the number of vertices. Vertex positions are
      expected to be floating values.
    line_color: a hexadecimal number representing RGB color of the line.
      Eg. 0xFF0000 is Red, 0x00FF00 is Green and 0x0000FF is Blue

  Returns:
    The BufferGeometry and Material of the line that can be added to a scene
    BufferGeometry is object describing the geometry of the line and which can
    be consumed by Three.js.
    Material is the color for the line.
  """
  context = _js_builder.Js(mode=_js_builder.PERSISTENT)
  vertices = context.Float32Array.new_object(line['vertices'].ravel().tolist())
  geometry = context.THREE.BufferGeometry.new_object()
  geometry.addAttribute('position',
                        context.THREE.BufferAttribute.new_object(vertices, 3))

  if 'color' in line.keys() and line['color'] is not None:
      material = context.THREE.LineBasicMaterial.new_object({'color': line['color']})
  else:
      # Draw a white line if no color is specified
      material = context.THREE.LineBasicMaterial.new_object({'color': 0xFFFFFF})

  return geometry, material
```

Thanks,
Kishore Venkateshan

**Comment by julienvalentin** [comment]
I am currently working on syncing github and google's internal repository. Once this is in place, it will be fine to create PRs. I anticipate to have all of that in place by the end of next week. I will let you know here when ready.

Regarding tests, a good guideline would be to follow the tests for quaternions for instance (https://github.com/tensorflow/graphics/blob/master/tensorflow_graphics/geometry/transformation/tests/quaternion_test.py). The same structure of tests is used throughout the codebase.

Best.

**Comment by kv3n** [comment]
Wonderful. Thank you so much. Appreciate the work you guys are putting in.

**Comment by julienvalentin** [comment]
I'll let you submit a PR when you get a chance. We will look at it then!

Best.
