### ISSUE TITLE
3d points perspective projection visibility

### ISSUE THREAD

**Issue by bhack** [tensorflow/graphics#17]
How do you inform the users about 3d point visibility in https://github.com/tensorflow/graphics/blob/master/tensorflow_graphics/rendering/camera/perspective.py#L170?

Here an interface with an extra output tensor for visibility in Matlab https://www.mathworks.com/matlabcentral/mlc-downloads/downloads/submissions/48752/versions/2/previews/projectPoints.m/index.html

See also https://github.com/opencv/opencv/issues/14703

**Comment by julienvalentin** [comment]
By default, 3d points have no volume, and hence, their projection has an area of 0. Visibility is then ill-defined in that context.

If you are after defining at most one point per pixel, one option is to create a grid that is MxN times bigger than the original image, project the 3points in that grid, and then perform spatial pooling to get back to the original image resolution.

**Comment by bhack** [comment]
Also in the one point per pixel context that I suppose it is a frequent use case for this API:
Suppose the case that you are in the context of regressing perspecitve projection input parameters can you go in inf/overflow with this product: https://github.com/tensorflow/graphics/blob/master/tensorflow_graphics/rendering/camera/perspective.py#L227

Cause you are not limited by any near and far plane and so you are not clipping in Homogeneous Clipping Coordinates?

I think it is hard to handle this with bigger MxN.

**Comment by julienvalentin** [comment]
If the near / far plane is your concern, you can always only pass data that satisfy your min / max depth. Would this not work for you?

Also, the solution I was describing was regarding the visibility problem, not the near/far plane.

**Comment by bhack** [comment]
Ok so you are just suggesting to let the user to filter 3d points before passing to the function to not have overflov in line 227?

**Comment by bhack** [comment]
Is there any case where `point_2d *= safe_ops.safe_signed_div(focal, depth)` can go to INF/NAN?

**Comment by julienvalentin** [comment]
This is effectively a division who's gradient behaves better than the normal division operator. I would then expect it go to INF if you divide a very large number by a very small one. Since a small epsilon is added to the denominator, I would think that it should not return NANs.

**Comment by bhack** [comment]
I think you can overflow if safe_ops.safe_signed_div is safe to not be NAN but point_2d is big.

**Comment by julienvalentin** [comment]
Indeed. If you need to handle large numbers, I would recommend to use double precision; it is going to be slower but would allow to handle much larger numbers than floats.

Is it safe to assume that I can close this ticket, or do you have any further questions on the matter of visibility?

**Comment by bhack** [comment]
If we suppose that is up to the user to filter the 3d points before the projection to not broke loss with inf/NAN we can close.
