### ISSUE TITLE
projection function for spherical harmonics

### ISSUE THREAD

**Issue by qianzhanginfo** [tensorflow/graphics#189]
The spherical harmonics rendering tutorial uses a tf_math.square_to_spherical_coordiantes projection to map the input square lighting function to a sphere. May I know the reason for this projection? Why not an equirectangular projection, which is used for environment maps?

`from tensorflow_graphics.math import math_helpers as tf_math

...

spherical_coordinates = tf_math.square_to_spherical_coordinates(normalized_pixels)

...`

**Comment by julienvalentin** [comment]
Hi @qianzhanginfo!

Spherical harmonics (SH) are defined on a sphere. The mapping you point at allows to get, per pixel, it's corresponding spherical coordinate. This mapping is used for displaying the lighting function on an image although defined on a sphere. Hope this helps.

Best.

**Comment by qianzhanginfo** [comment]
Thanks! Does this mapping apply to any lighting function defined on a sphere, including the equirectangular environment map? I would appreciate it if you could point to a reference for the square_to_spherical_coordinates mapping.

And it seems the height and width are swapped in the tutorial.

**Comment by julienvalentin** [comment]
I would encourage you to use your favorite search engine for this ;)
