### ISSUE TITLE
Tensorflow.js implementation

### ISSUE THREAD

**Issue by SpicySyntax** [tensorflow/graphics#20]
Preface: This is more of a question than an issue with the repo.

Are there any plans to expose the tensorflow graphics api to be used with Tensorflow.js?

If not I may consider, writing a port of this project to tensorflow.js.

Thanks!

**Comment by julienvalentin** [comment]
Hi @SpicySyntax 

This is not something we are planning to do internally, but more than happy for you to take a stab at it!

Best.
