### ISSUE TITLE
Integrating Mesh-RCNN as part of Tensorflow-Graphics (GSoc 20)

### ISSUE THREAD

**Issue by MadhavEsDios** [tensorflow/graphics#208]
My sincerest apologies for opening a completely unrelated issue. I wanted to get in touch with potential mentors who would oversee the MeshRCNN in Tensorflow-Graphics project, as I had a couple of important questions to ask.

Again I am sorry for opening an issue with regards to a problem that does not yet exist.

**Comment by osanseviero** [comment]
Hello Madhav!

Sorry for the late reply. Unfortunately, the applications for GSOC have closed. We plan to create some [good first issue] and [contributions welcome] issues if you want to contribute to TF Graphics. 

Thank you!

**Comment by MadhavEsDios** [comment]
Hi @osanseviero , unfortunately it seems that due to the pandemic, I am not eligible to participate in GSoC, as I could not finalize my admission into a Master's program due to a lockdown in my country.
However, I would still like to work on this project voluntarily (unless some eligible student's proposal has already been selected).
If you do not mind, I would really appreciate if you could go through the proposal that I had originally uploaded to my GSoC'20 dashboard.
**Proposal**: [https://github.com/MadhavEsDios/GSoC-20-Proposal](https://github.com/MadhavEsDios/GSoC-20-Proposal)
**Note**: I can also send my CV and answers to the GSoC questions to your personal e-mail, if you find my proposal good enough.

Thanks !
