### ISSUE TITLE
Threejs Visualization

### ISSUE THREAD

**Issue by frankhome61** [tensorflow/graphics#21]
Hi! I am currently working on a visual localization project and would like to use some visualization tools like threejs mentioned in some of the tutorials. Currently, when importing tensorflow_graphics, I see a warning stating:
 "To use the threejs_vizualization, please install the colabtools package following the instructions detailed in the README at github.com/tensorflow/graphics." I am having a hard time finding the package and I am thus asking if such package exists, and if so, how could I install it? Thanks!

**Comment by julienvalentin** [comment]
Please note that colabtools is only compatible with Colab.
