### ISSUE TITLE
Missed import in tensorflow/graphics/rendering/__init__.py

### ISSUE THREAD

**Issue by frankhome61** [tensorflow/graphics#22]
Hi! I found this issue when importing the differentiable renderer module (which was pushed last night), that the module was not imported in graphics/rendering/__init__.py after line 20. I believe adding this import should fix the issue.

**Comment by julienvalentin** [comment]
Hi @frankhome61 

Thanks for raising this, I will have a look at this shortly.

Best.

**Comment by julienvalentin** [comment]
This has been resolved. Thanks for reporting!
