### ISSUE TITLE
https://www.tensorflow.org/graphics colab example broken

### ISSUE THREAD

**Issue by isaacgerg** [tensorflow/graphics#224]
This does not work out of the box.
```
import numpy as np
import tensorflow as tf
import trimesh

import tensorflow_graphics.geometry.transformation as tfg_transformation
from tensorflow_graphics.notebooks import threejs_visualization

tf.enable_eager_execution()  # should be tf.compat.v1.enable_eager_execution()

# Download the mesh.
!wget https://storage.googleapis.com/tensorflow-graphics/notebooks/index/cow.obj
# Load the mesh.
mesh = trimesh.load("cow.obj")
mesh = {"vertices": mesh.vertices, "faces": mesh.faces}
# Visualize the original mesh.
threejs_visualization.triangular_mesh_renderer(mesh, width=400, height=400)
# Set the axis and angle parameters.
axis = np.array((0., 1., 0.))  # y axis.
angle = np.array((np.pi / 4.,))  # 45 degree angle.
# Rotate the mesh.
mesh['vertices'] = tfg_transformation.axis_angle.rotate(mesh["vertices"], axis,
                                                        angle).numpy()
# Visualize the rotated mesh.
threejs_visualization.triangular_mesh_renderer(mesh, width=400, height=400)

```

**Comment by fulkast** [comment]
@isaacgerg May you give some more information about what you are seeing, e.g. any error messages, prompts etc.?

**Comment by isaacgerg** [comment]
```

AttributeErrorTraceback (most recent call last)

<ipython-input-2-7db5433f8205> in <module>()
     10 from tensorflow_graphics.notebooks import threejs_visualization
     11 
---> 12 tf.enable_eager_execution()

AttributeError: 'module' object has no attribute 'enable_eager_execution'
```

**Comment by fulkast** [comment]
> ```
> 
> AttributeErrorTraceback (most recent call last)
> 
> <ipython-input-2-7db5433f8205> in <module>()
>      10 from tensorflow_graphics.notebooks import threejs_visualization
>      11 
> ---> 12 tf.enable_eager_execution()
> 
> AttributeError: 'module' object has no attribute 'enable_eager_execution'
> ```

Have you tried changing the line

`tf.enable_eager_execution()` to

`tf.compat.v1.enable_eager_execution()`?

**Comment by isaacgerg** [comment]
@fulkast Hi, I did do this as shown in my comments in the first post.  I am able to fix the error no problem. I filed a github issue so the documentation is fixed on the website.

**Comment by julienvalentin** [comment]
Thanks for raising and submitting a fix. The PR is in internal review and your changes deployed soon!

**Comment by osanseviero** [comment]
This is fixed now :) Thanks @Molkree for the fix!

**Comment by Molkree** [comment]
Code snippet on the page still shows old code though.

**Comment by osanseviero** [comment]
Page is updated. Thanks!
