### ISSUE TITLE
Model failing to serialise as JSON while saving using model.Save()

### ISSUE THREAD

**Issue by rlav440** [tensorflow/graphics#227]
**System setup**
Ubuntu 19.10
TF versions 2.1.0 and 2.20 current nightly tested
TF-graphics built from current git source

**Error Behaviour**
Model is defined using Keras Functional API, attempts to reproduce the example Mesh segmentation on a different dataset. Uses the FeatureSteeredConvolutionKerasLayer to do this.
While saving raises this message:
```
WARNING:tensorflow:Model failed to serialize as JSON. Ignoring... Layer FeatureSteeredConvolutionKerasLayer has arguments in `__init__` and therefore must override `get_config`.
```
Saving eventually fails with the message
```
ValueError: If specifying TensorSpec names for nested structures, either zero or all names have to be specified.
```

**Code and minimal sample dataset**
[Minimal_code.zip](https://github.com/tensorflow/graphics/files/4465845/Minimal_code.zip)
[Dataset1.zip](https://github.com/tensorflow/graphics/files/4465846/Dataset1.zip)

**Comment by rlav440** [comment]
In writing a minimal code example, I found that removing the graph convolution layers allows the model to save - so the error is dependant on TF_graphics

**Comment by jackd** [comment]
`get_config` and keras object registration [here](https://github.com/tensorflow/graphics/pull/242).

**Comment by julienvalentin** [comment]
With your thumbs up I assume that your problem is solved; closing.
Feel free to re-open if that is not the case!

**Comment by rlav440** [comment]
Hey, sorry - the issue isn't fixed: I haven't tested the proposed commit yet personally. I've been recompiling/loading the weights rather than using models.load_model() in the mean time as a temporary workaround. If it would be useful, I can prioritise confirming that the pull request solves my issue.
(can't reopen issue as I'm not a collaborator)
Cheers!

**Comment by jackd** [comment]
Can confirm the error is related to serialization (though I suspect loading the saved model would not be possible without fixing the serialization issue). I suspect this is an issue for the tf core / keraas team though (I'm not a contributor though, just an interested party :) ).

**Comment by rlav440** [comment]
Thanks for the insight: I'm looking to get my model ready for a deadline next week so I'll hopefully verify your suspicions in the next few days.
