### ISSUE TITLE
[details] tf graphics colab for mesh segmentation broken

### ISSUE THREAD

**Issue by chrysmun** [tensorflow/graphics#229]
hi, si out of box the mesh segmentation colab is broken.

imho the colab loads tf 2.2 which is incompatible with the current tfgraphics.
oddly locally it works with tf1.14 but trains for 1 second and stops.

the example used to work i know in january/february. now the error message in colab is:

WARNING: Logging before flag parsing goes to stderr.
W0413 15:27:09.518968 139640493516672 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow_graphics/notebooks/mesh_segmentation_dataio.py:173: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.experimental.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_deterministic`.

AttributeErrorTraceback (most recent call last)
<ipython-input-5-0049de5dbd79> in <module>()
     10 with input_graph.as_default():
     11   mesh_load_op = dataio.create_input_from_dataset(
---> 12       dataio.create_dataset_from_tfrecords, test_tfrecords, test_io_params)
     13   with tf.Session() as sess:
     14     test_mesh_data, test_labels = sess.run(mesh_load_op)

/usr/local/lib/python2.7/dist-packages/tensorflow_graphics/notebooks/mesh_segmentation_dataio.pyc in create_input_from_dataset(dataset_fn, files, io_params)
    325 
    326   dataset = dataset_fn(files, io_params)
--> 327   mesh_data = dataset.make_one_shot_iterator().get_next()
    328   mesh_data['neighbors'] = adjacency_from_edges(mesh_data['edges'],
    329                                                 mesh_data['edge_weights'],

AttributeError: 'PaddedBatchDataset' object has no attribute 'make_one_shot_iterator'

**Comment by osanseviero** [comment]
Hi @chrysmun. Thanks for reporting this. The Mesh Segmentation colab only works with TF 1 for now. There's already a [PR](https://github.com/tensorflow/graphics/pull/215) solving this issue.

**Comment by osanseviero** [comment]
Hello @chrysmun. This issue is solved now. Thanks for reporting it!
