### ISSUE TITLE
Merge tensorflow-graphics-gpu and tensorflow-graphics

### ISSUE THREAD

**Issue by ataiya** [tensorflow/graphics#230]
Since version 1.15 (November 2019) TensorFlow has dropped the -gpu version of their repos.
There is now no difference between these two install modes:

```
pip install tensorflow
pip install tensorflow-gpu
```

Simply, the GPU versions are used if GPUs + drivers + libraries are available
To be consistent with the parent repo, we should also adopt the same structure for TFG?

**Comment by julienvalentin** [comment]
Yes we should certainly do that for the next release of the package; Thanks for raising.
