### ISSUE TITLE
Microfacet-based BRDF models

### ISSUE THREAD

**Issue by anandbhattad** [tensorflow/graphics#24]
Hi, 
Do you have any plans for building a microfacet-based BRDF model?
Thanks!

**Comment by julienvalentin** [comment]
This is something we have talked about and on the roadmap, but quite low priority for now. Would you be interested in implementing it?

Best.

**Comment by dknyxh** [comment]
I'm also interested in this. I haven't done much research on this. My question is that are usual microfacet-based BRDF models differentialable? If so, for a starter, would the implementation be similar to blinn-phong reflectance module?

**Comment by francoisruty** [comment]
Don't microfacet-based BRDF require some sort of random sampling at some point in the process? 
I'm not 100% sure but I think if there's randomness it can't be differentiable

**Comment by julienvalentin** [comment]
@dknyxh you can have a read at http://simonstechblog.blogspot.com/2011/12/microfacet-brdf.html which I found was a good resource to understand the most common approximation. Unless I am missing something, it indeed looks differentiable ;)

**Comment by dknyxh** [comment]
> @dknyxh you can have a read at http://simonstechblog.blogspot.com/2011/12/microfacet-brdf.html which I found was a good resource to understand the most common approximation. Unless I am missing something, it indeed looks differentiable ;)
> 
> I indeed envision the implementation to be similar to the existing reflectance functions.

Thanks so much for the pointers. I'll see if I can implement this.

**Comment by julienvalentin** [comment]
Hi @dknyxh 

Any update on this front?

Best.

**Comment by dknyxh** [comment]
@julienvalentin Sorry. I haven't got time to do this and my project which is supposed to use this is going into another direction.

**Comment by osanseviero** [comment]
Reopening this issue since it already has a pointer. Would anyone be interested on implementing it?
