### ISSUE TITLE
keras mesh segmentation implementation?

### ISSUE THREAD

**Issue by jackd** [tensorflow/graphics#246]
I recently hacked up a quick [tf.keras port](https://gist.github.com/jackd/f62cfc5e548876fc05af5610587f0704) port of the mesh segmentation demo notebook. Is there any interest in me pretty-ing it up for a notebook contribution?

**Comment by avneesh-sud** [comment]
hi jackd@!

Thanks for this offer - we definitely welcome a keras version of the notebook!
