### ISSUE TITLE
Pool and Unpool Usage

### ISSUE THREAD

**Issue by simofoti** [tensorflow/graphics#25]
Hi! 

I would like to use the pooling and unpooling operators (in a CNN) to sample and upsample a mesh, but I am not sure I've properly understand their implementation.
In particular, I would like to know how to use the pool_map and how to get the new edges/adjacency_matrix after applying the operation.

Could you provide a quick example of their usage and/or some reference?

**Comment by julienvalentin** [comment]
Hi,

Did you have the chance to look at our tests?

Best.

**Comment by simofoti** [comment]
@julienvalentin thanks for your quick response. Yes, I had a look at them and at three of them in particular:
-  *test_pool_identity* 
-  *test_pool_random*
 - *test_pool_preset*

However I don't understand how to generate a pool_map automatically. I get how to create it manually, but I would ideally like to pool meshes with thousand of vertices taking into account their edge connectivity/adjacency matrix. Do you have a function to compute it or should I implement it?

**Comment by Epsilon1024** [comment]
I'm looking at the pooling tests too and do not completely understand how the pooling map works.  The original FeastNet paper used the Graclus algorithm to create clusters and then placed them into a binary tree before pooling.  How does it work in the Tensorflow implementation?

**Comment by simofoti** [comment]
@Epsilon1024 in my understanding you have to define a pooling map where the number of columns is equal to the number of vertices and the number of rows is equal to the number of vertices you want to obtain after pooling. Each row of this matrix is the set of weights that will determine the features of the new vertices with respect to the old ones.

A quick example might be the following: you have 4 vertices with 2 features each and you want to obtain only two vertices. Setting up a pooling matrix like: 

[[ 0.5,  0.5,  0,     0],
 [ 0,     0,     0.5,  0.5 ]]

you average the features of the first and second vertex to get one node and the features of the third and forth to get the other node. 

|                          |        |        |       |       |
|----------------------|------|------|-----|-----|
|**pre pooling**   | 0 1 | 2 3 | 4 5| 6 7|
|**after pooling** |       | 1 2 | 5 6 |     |

However, I am still trying to understand how to get the new adjacency matrix or face list out of it. @julienvalentin  do yu have any suggestion?

**Comment by julienvalentin** [comment]
@amakadia has implemented this part of the codebsae, I will ask him to get back to you as soon as time allows.

**Comment by amakadia** [comment]
> @Epsilon1024 in my understanding you have to define a pooling map where the number of columns is equal to the number of vertices and the number of rows is equal to the number of vertices you want to obtain after pooling. Each row of this matrix is the set of weights that will determine the features of the new vertices with respect to the old ones.

Hi @simofoti 
We implemented this pooling and unpooling to be quite general and not tied to any specific pooling algorithm. Your understanding here is correct. I would only add that the code also offers 'max' pooling which will ignore the set of weights since it is taking the max and not a linear combination.

> 
> A quick example might be the following: you have 4 vertices with 2 features each and you want to obtain only two vertices. Setting up a pooling matrix like:
> 
> [[ 0.5, 0.5, 0, 0],
> [ 0, 0, 0.5, 0.5 ]]
> 
> you average the features of the first and second vertex to get one node and the features of the third and forth to get the other node.
> 
> **pre pooling**	0 1	2 3	4 5	6 7
> **after pooling**		1 2	5 6	
> However, I am still trying to understand how to get the new adjacency matrix or face list out of it. @julienvalentin do yu have any suggestion?

We do not yet provide a method to get a new adjacency after pooling, partly because there can be many ways to determine this. For now, users will have to provide both the pooling map and the new adjacency. It wouldn't be a bad idea to have some example routines for calculating the pooling maps and pooled-graph adjacencies (e.g. Graclus), but we don't have a concrete plan for this right now.

**Comment by amakadia** [comment]
Although i mentioned in my last note
