### ISSUE TITLE
Graph Embedding 

### ISSUE THREAD

**Issue by didukhle** [tensorflow/graphics#27]
Good evening,
 
Is it planned to implement the Graph Embedding for this library? Best, Leonid

**Comment by julienvalentin** [comment]
Not planned right this second, but happy to take contributions in this direction.
Did you have specifics in mind?

Best.

**Comment by avneesh-sud** [comment]
Hi Leonid - can you share specifics of graph embeddings that you have in mind? Currently there are no plans to provide complete models in tensorflow-graphics, rather the underlying ops and layers. For graphs, 2 graph convolution layers are provided: FeatureSteeredConvolution and DynamicGraphConvolution, and  mesh_segmentation_demo shows how to construct a mesh  (special case of a graph)  embedding for node classification.

**Comment by didukhle** [comment]
Thank you for your answer. The idea to have an Embedding layer that map graph (represented as a weighted adjacency matrix) or node of the graph to the n-dim vector, with random walks. 
Best.

**Comment by julienvalentin** [comment]
I must be missing something obvious, but I don't see how this is related to computer graphics?

**Comment by julienvalentin** [comment]
Inactive thread, closing.
