### ISSUE TITLE
Numerical Instability Issue with cartesian_to_spherical_coordinates when using TF 2.2 RC4

### ISSUE THREAD

**Issue by oracle3001** [tensorflow/graphics#283]
Using the latest TFG code from Github, TF 2.2.0 RC4, Python 3.7 on a Windows 10 box,  when using cartesian_to_spherical_coordinates function there appears to be some numerical instability has been introduced. Using TF 2.1 doesn't have this issue.

A set of points located on the surface of a unit sphere (provided in the zip file) and running the following code, results in the following output. 

[test_control_vert_pos.zip](https://github.com/tensorflow/graphics/files/4563910/test_control_vert_pos.zip)

```
import pandas as pd
import numpy as np
import tensorflow as tf

from tensorflow_graphics.math import math_helpers
df = pd.read_csv('test_control_vert_pos.csv', header=None)
test_pos = df.values.astype('float32')

all_pos_spherical = math_helpers.cartesian_to_spherical_coordinates(test_pos).numpy()
selected_pos_spherical = math_helpers.cartesian_to_spherical_coordinates(test_pos[20:23, :]).numpy()

print(all_pos_spherical[20:23, :])
print(selected_pos_spherical)
```

Using TF 2.2
-------------
all_pos_spherical[20:23, :]
---------------------------
[[ 0.99999994         nan -0.        ]
 [ 0.99999994  1.5707964   1.5707964 ]
 [ 0.99999994         nan  3.1415927 ]]

selected_pos_spherical
-------------------------
[[ 1.         0.        -0.       ]
 [ 1.         1.5707964  1.5707964]
 [ 1.         3.1415927  3.1415927]]

Using TF 2.1
-------------
all_pos_spherical[20:23, :]
---------------------------
[[ 1.         0.        -0.       ]
 [ 1.         1.5707964  1.5707964]
 [ 1.         3.1415927  3.1415927]]

selected_pos_spherical
-------------------------
[[ 1.         0.        -0.       ]
 [ 1.         1.5707964  1.5707964]
 [ 1.         3.1415927  3.1415927]]

**Comment by julienvalentin** [comment]
Thanks for reporting this @oracle3001 !
We submitted a patch https://github.com/tensorflow/graphics/pull/284

Feel free to re-open in case the problem did not completely dissapeared.
