### ISSUE TITLE
Numerical Instability Issue with cartesian_to_spherical_coordinates (reopen)

### ISSUE THREAD

**Issue by oracle3001** [tensorflow/graphics#306]
Firstly, sorry for the new post, I can't see how to reopen the original issue.

As previous reported on #283 , this issue is still present when using the latest pull from tensorflow graphics repository and using Tensorflow 2.2 (official release). 

All the same test code / resultant output as previously described.

**Comment by oracle3001** [comment]
Edit :- I believe I have worked out the issue.

The problem only appear to arise when using a version of tensorflow that has been built to make use of AVX2 optimization.

**Comment by cem-keskin** [comment]
We added multiple unittests to ensure that everything works as intended, and tested with avx2 optimization but couldn't reproduce this issue internally. This doesn't seem to be a TF Graphics bug, but it could be TF2.2 related.

As a workaround we will introduce an epsilon parameter for the cartesian_to_spherical_coordinates function today. By setting it to an appropriate value like 1e-7 you can get rid of the NaN values. Or you can use float64, which also seems to fix the issue.
