### ISSUE TITLE
Use TFDS mock_data for pointnet_test

### ISSUE THREAD

**Issue by ataiya** [tensorflow/graphics#309]
Currently [this test](https://github.com/tensorflow/graphics/blob/master/tensorflow_graphics/projects/pointnet/train_test.py) uses logic that does not provide 100% code coverage; see the effect [here](https://github.com/tensorflow/graphics/blob/master/tensorflow_graphics/projects/pointnet/train.py#L133), where L133..L157 are not covered.

However, TFDS does provide functionality to have "fake" data imported:
https://www.tensorflow.org/datasets/api_docs/python/tfds/testing/mock_data

@jackd are you interested in playing with this? :)

**Comment by jackd** [comment]
Writing tests? For other people's code? On data pipelining? On a weekend?

... you're lucky I'm in [quarantine](https://www.smartraveller.gov.au/while-youre-away/returning-australia) ;). https://github.com/tensorflow/graphics/pull/310

**Comment by ataiya** [comment]
I hear you :) – I am doing the same – fantastic!

By the way, these are the project coding templates/example, so whatever we modify has a large potential impact to follow-up contributions. That is why I am investing in polishing the code as much as possible now. 

In this regard, I discussed with the TSDF folks last night. My hope was that via this mechanism, and a tweak to modelnet40.load(...), it should be possible to avoid the dry-run flag completely from the test, and have the mock_data be completely isolated to the test class?

**Comment by ataiya** [comment]
@jackd feel free to close once the PR gets published.
Reassigning to you.

**Comment by jackd** [comment]
@ataiya PR is merged, but I can't close.

**Comment by julienvalentin** [comment]
Hi @jackd 

We have to limit rights on Github until we switch to using Github first. Note that we are working on the transition from Google repo first to Github first.

Closing

Best.
