### ISSUE TITLE
layer names

### ISSUE THREAD

**Issue by jackd** [tensorflow/graphics#314]
Style request: can layer names conform to tensorflow conventions? Specifically:
* no appended `Layer` or `KerasLayer` to `tf.keras.layers.Layer` implementations - it should be obvious from the module (e.g. `tf.nn.layer`) and convention.
* no naming of functions finishing in `layer` if they aren't returning / using a `tf.keras.layers.Layer`.

Happy to put in a PR with these changes (non-breaking with deprecated warnings on existing functions) if it's a desired direction.

I'd also love the `layer` submodule renamed `layers`, but that's probably a bit much to ask at this point (though if that's desired by others I can do this as well).

**Comment by julienvalentin** [comment]
Hi @jackd !

Makes sense! Let's maybe start with one of these layers to see what the suggested change implies?

Best.

**Comment by ataiya** [comment]
+1 to both

I think via some __init__.py magic you could get layer → layers (agreed it is better) change to be non-breaking. TF does a fair bit of __init__ magic in this sense too.
