### ISSUE TITLE
AttributeError: 'int' object has no attribute 'value' in tf2.2

### ISSUE THREAD

**Issue by kohei-tofu** [tensorflow/graphics#323]
Is this line correct?

tensorflow_graphics/util/shape.py:135
**135 : return tensor.shape[axis].value**
It is comming from 
**tensorflow_graphics/geometry/transformation/quaternion.py:555 rotate**

I run tutorial for beginner in tf2.2, this error occured.

**Comment by jackd** [comment]
I think the pip version is only compatible with tf 1.x. I'd suggest cloning/installing from master.

**Comment by julienvalentin** [comment]
As @jackd mentioned, our pip package on pypi needs update. Please clone the repository.
