### ISSUE TITLE
Install of TF-Graphics is not handling existing installed TF versions properly

### ISSUE THREAD

**Issue by oracle3001** [tensorflow/graphics#325]
Using the latest code from Github (as of 14/05), there is an issue when you use pip install the whl file.

Tensorflow 2.2 is now the gpu version by default. If you have this installed, when you go to pip install a gpu build of tensorflow graphics, the install system doesn't realise this and thus downloads / installs the specifically named tensorflow-gpu-2.2.0 over the top.

**Comment by ataiya** [comment]
Hi @oracle3001, do you mind trying with version "2020.5.20", I think you were still using "1.0"
@julienvalentin recently pushed it to [PyPi](https://pypi.org/project/tensorflow-graphics)

I will also move the tfg-nightly from test.pypi to pypi proper early next week.

**Comment by oracle3001** [comment]
It handles tensorflow 2.2 ok, however it doesn't handle tensorflow 2.3 (i.e tf nightly). 

Using pip install --upgrade tfg-nightly command

It still tries to install the older stable tensorflow v2.2

**Comment by ataiya** [comment]
@julienvalentin should we make tfg-nightly depend on tfg-nightly rather than tensorflow proper? 

This would resolve the problem, I think

**Comment by julienvalentin** [comment]
sure; will create the PR

**Comment by ataiya** [comment]
@oracle3001 the nightly package deployment tonight will depend on tf-nightly.
Please re-open the issue if you think this does not solve it, with the steps to reproduce it.

Thanks
