### ISSUE TITLE
Setup nightly distribution with GitHub Actions

### ISSUE THREAD

**Issue by ataiya** [tensorflow/graphics#342]
https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

**Comment by ataiya** [comment]
Created testpypi user; see valentine password storage
Using [settings/secrets](https://github.com/tensorflow/graphics/settings/secrets) to store passwords securely

Tested on [my fork](https://github.com/ataiya/graphics), works "as advertised":
https://test.pypi.org/project/tfg-nightly/

To test deployment, see here:
https://packaging.python.org/tutorials/packaging-projects/#installing-your-newly-uploaded-package

**Comment by Molkree** [comment]
It is [UTC](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onschedule).

> at specific **UTC** times using POSIX cron syntax

**Comment by ataiya** [comment]
Release candidate in #347

**Comment by ataiya** [comment]
Started transition to PyPi proper.

**Comment by gitlabspy** [comment]
how about tfg-nightly-gpu?

**Comment by taiya** [comment]
There's no difference between the two packages any longer.
