### ISSUE TITLE
Is the data_formats module redundant?

### ISSUE THREAD

**Issue by drebain** [tensorflow/graphics#343]
It looks like `tensorflow_graphics.io` and `tensorflow_graphics.util.data_formats` have the same purpose. Should `util.data_formats` be deprecated and pointed to `io`?

**Comment by julienvalentin** [comment]
Good point; raising this with Aviv who created the .io

**Comment by segaviv** [comment]
Thanks for pointing this out!
I wasn't aware of util.data_formats when creation the io package and they indeed serve the same purpose.

I'll move the exr reader & write to tfg.io package.

**Comment by julienvalentin** [comment]
@segaviv I think you covered this in a recent push. I let you close this if this issue if this is the case.

**Comment by segaviv** [comment]
Yes, this is now resolved, however I don't seem to have permissions to close the issue I think.
