### ISSUE TITLE
Not Found Tourial

### ISSUE THREAD

**Issue by SaberArthurus** [tensorflow/graphics#346]
Hi, 
I can not access https://github.com/tensorflow/graphics/blob/master/tensorflow_graphics/g3doc/api_docs/python/tfg.md.

Best

**Comment by julienvalentin** [comment]
Hi @SaberArthurus 

We are in the middle of changing how the documentation is published on the web. In the meantime, you can either clone a version of the repo where this file existed, or refer to the documentation directly in the python files.

Best.
