### ISSUE TITLE
Jupyter Notebook name '_publish' is not defined

### ISSUE THREAD

**Issue by Dawars** [tensorflow/graphics#4]
The example colab (https://colab.research.google.com/github/tensorflow/graphics/blob/master/tensorflow_graphics/notebooks/mesh_segmentation_demo.ipynb) breaks in a local tensorboard installation. 

Because of this line:
https://github.com/tensorflow/graphics/blob/master/tensorflow_graphics/notebooks/threejs_visualization.py#L25

``` 
NameError                                 Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/tensorflow_graphics/notebooks/threejs_visualization.py in build_context()
     72   """Builds a javascript context."""
     73   threejs_url = 'https://www.gstatic.com/external_hosted/threejs-r98/'
---> 74   _publish.javascript(url=threejs_url + 'three.min.js')
     75   _publish.javascript(url=threejs_url + 'examples/js/controls/OrbitControls.js')
     76   return _js_builder.Js(mode=_js_builder.PERSISTENT)

NameError: name '_publish' is not defined
```

I installed the packages by running :
```
pip3 install tf-nightly-gpu tb-nightly future tensorflow-graphics-gpu
```
On an Ubuntu18.04 LTS machine with anaconda 3.7.3

**Comment by Dawars** [comment]
```
'Warning: To use the threejs_vizualization, please install the colabtools'
      ' package following the instructions detailed in the README at'
      ' github.com/tensorflow/graphics
```
I found this warning and I followed the instructions. 
There are no instruction regarding the installation of colabtools.
This repo also seems to be outdated: https://github.com/googlecolab/colabtools

**Comment by julienvalentin** [comment]
Hi David,

Unfortunately colabtools is not compatible with Jupyter at this time, and it does not seem that this is something the maintainers have on their agenda for now. If you wish to visualize 3D things, I would recommend to have a look at our 3D TensorBoard. One internal contributor is looking at removing the renderer currently used in the Colab demos and which depends on colabtools. The aim is to replace that with our 3D TensorBoard. I will send a message on twitter (@_TFGraphics_) once this is submitted.

Best.

**Comment by julienvalentin** [comment]
I am closing this; feel free to re-open if you have further questions

**Comment by XuankeShi** [comment]
> The example colab (https://colab.research.google.com/github/tensorflow/graphics/blob/master/tensorflow_graphics/notebooks/mesh_segmentation_demo.ipynb) breaks in a local tensorboard installation.
> 
> Because of this line:
> https://github.com/tensorflow/graphics/blob/master/tensorflow_graphics/notebooks/threejs_visualization.py#L25
> 
> ```
> NameError                                 Traceback (most recent call last)
> /opt/conda/lib/python3.7/site-packages/tensorflow_graphics/notebooks/threejs_visualization.py in build_context()
>      72   """Builds a javascript context."""
>      73   threejs_url = 'https://www.gstatic.com/external_hosted/threejs-r98/'
> ---> 74   _publish.javascript(url=threejs_url + 'three.min.js')
>      75   _publish.javascript(url=threejs_url + 'examples/js/controls/OrbitControls.js')
>      76   return _js_builder.Js(mode=_js_builder.PERSISTENT)
> 
> NameError: name '_publish' is not defined
> ```
> 
> I installed the packages by running :
> 
> ```
> pip3 install tf-nightly-gpu tb-nightly future tensorflow-graphics-gpu
> ```
> 
> On an Ubuntu18.04 LTS machine with anaconda 3.7.3

i have the same problem,did you solve it,i don't no why ,i use tf1.4   cuda10.

**Comment by julienvalentin** [comment]
@XuankeShi are you using Jupyter? Right now the 3d visualizer that is supplied in the Colab demos is only compatible with Colab, and unfortunately is not compatible with Jupyter notebooks. @podlipensky is looking into upgrading these to using the TensorBoard visualizer and might be able to comment further.

**Comment by podlipensky** [comment]
For now I'd suggest to just do 
```
pip3 install tb-nightly
```
Because `tf-nightly` can override some of the dependencies (my wild guess here). We'll investigate it further soon.
