### ISSUE TITLE
CvxNet is the dual transformation actually used?

### ISSUE THREAD

**Issue by themasterlink** [tensorflow/graphics#400]
Hey,

I have a question regarding the max operation defined below eq. 3 in your paper.

<img src="https://render.githubusercontent.com/render/math?math=\hat{O}(x) = max_k\{C_k(x)\}">

As I understand all convexes are parameterized and then transformed to their location (see Fig. 7).
However, there is no step, which avoids that convexes are much bigger than the actual object boundaries as long as the max operation over all convexes is correct. If I understood that incorrectly, can you please point me to the constraint you add to make sure this does not happen.

This also means that it is not possible to actually use the dual transformation, as the convexes only have the right object boundary if combined through a max operation. Checking the code for the mesh extraction, I expected to see this dual transformation but instead you are using a marching cubes, which in your paper and I quote: 
> Conversely, as we illustrate in Figure 6, we only require the execution of two duality transforms, and the computations of two convex hulls of H points. The complexity of these operations is clearly independent of any resolution parameter ε.

I am referring to this code piece here:

https://github.com/tensorflow/graphics/blob/946aa03b5178d2fc557a81045b84df24af322afd/tensorflow_graphics/projects/cvxnet/lib/utils.py#L164-L166

Can you please clarify this for me?

**Comment by Awcrr** [comment]
Hi Maximilian,

I'm Boyang Deng, one of the authors of CvxNet. Thanks for your interests in our work! I'm sorry I noticed your issue just today.

> However, there is no step, which avoids that convexes are much bigger than the actual object boundaries as long as the max operation over all convexes is correct
This is a good point! We also considered this in this work. Please note that we have a $L_{unique}$ loss (see Eq. (5) in the paper) which can help with this case. Basically, it will ask the model to predict the minimal sized convex polytopes that can explain the sample points. Therefore, even after the max operation the results are the same, this loss will shrink the super big convex by pulling the hyperplanes to be tightly around the target, of course also within the bounding boxes.

> Checking the code for the mesh extraction, I expected to see this dual transformation but instead you are using a marching cubes, which in your paper and I quote:
Right, here we use marching cube to align our quantitative evaluation with previous methods. But we also have a script to do the double dual operation to extract surfaces directly. We are working on cleaning up that script. Hopefully, we will release this soon.

Please let me know if this resolve your issues :)

**Comment by taiya** [comment]
For the direct convex computation, @Awcrr you know where to find it ;)
`experimental/users/atagliasacchi/cvxnet/blender.py`

**Comment by themasterlink** [comment]
Hey Boyang,

> Basically, it will ask the model to predict the minimal sized convex polytopes that can explain the sample points. Therefore, even after the max operation the results are the same, this loss will shrink the super big convex by pulling the hyperplanes to be tightly around the target, of course also within the bounding boxes.

Thanks for this explanation that clears that  up.

>  But we also have a script to do the double dual operation to extract surfaces directly. We are working on cleaning up that script. Hopefully, we will release this soon.

Then I can't wait to see this script, as I see this as one of the major contributions of this work.

PS: It seems Andrea already knows where it is ;)

**Comment by themasterlink** [comment]
Any news on this? 

Max

**Comment by Awcrr** [comment]
Hi Max, I really sorry for this delay. It's been a busy and tough 6-month for me.

I'll get to this after the holiday. I think ETA of this script update can be Mid-January, like 15-20.

Hope this didn't cause too many troubles for you.

**Comment by themasterlink** [comment]
Is it better now?

Best,
Max

**Comment by taiya** [comment]
@themasterlink the only two functions you need are these:

```
def halfspaces_to_vertices(halfspaces):
  """
  HP: euclidean origin is within the halfspaces
  Input: Hx(D+1) numpy array of halfplane constraints
  Output: convex hull vertices
  """
  n_dims = halfspaces.shape[1]-1
  from scipy.spatial import HalfspaceIntersection
  feasible_point = np.zeros([n_dims,])
  hs = HalfspaceIntersection(halfspaces, feasible_point)
  return hs.intersections

def vertices_to_convex_TRIMESH(vertices):
  import trimesh
  mesh = trimesh.Trimesh(vertices=vertices, faces=None)
  return mesh.convex_hull.vertices, mesh.convex_hull.faces
```

which are used in a control loop as: 
```
  for iC in range(C):
    cvx_halfspaces = obj_shape[iC, ...]
    cvx_translation = obj_trans[iC, ...]
    vertices = halfspaces_to_vertices(cvx_halfspaces)
    vertices, faces = vertices_to_convex_TRIMESH(vertices)
    vertices += cvx_translation
    plot_wireframe(ax, vertices, faces)
```

This should be able to get you started.
