### ISSUE TITLE
Cvxnet: Cython missing in requirements

### ISSUE THREAD

**Issue by theRealSuperMario** [tensorflow/graphics#430]
To run `python setup.py build_ext --inplace`, you need cython which is missing in the requirements.

**Comment by engrmz** [comment]
Hi,
I have trained the model for RGB-to-3D and Depth-to-3D. Now, I am running the eval.py for evaluation of the trained models. However, there is an error for both the cases as shown below;

`tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_3' with dtype float
	 [[node Placeholder_3 (defined at /code/cvxnet/graphics/tensorflow_graphics/projects/cvxnet/eval.py:67) ]]`

I did not change any parameters. Can anyone please let me know what is the error here? I am new in tensorflow :) Thanks in advance.

-mz

**Comment by Awcrr** [comment]
Thanks for pointing this out! A good catch! We updated the dependency with cython included.
