### ISSUE TITLE
Format bug in `bspline.interpolate` docs

### ISSUE THREAD

**Issue by mtsokol** [tensorflow/graphics#433]
Hi!

In: https://www.tensorflow.org/graphics/api_docs/python/tfg/math/interpolation/bspline/interpolate 
formatting broken doc by [introducing `-` at the beginning of the line](https://github.com/tensorflow/graphics/blob/master/tensorflow_graphics/math/interpolation/bspline.py#L253).

Can it be fixed manually or is it standard formatting (so text should be changed)?
If so, let me know if I can try to fixed it :)

**Comment by osanseviero** [comment]
Hi Mateusz! Sorry for the delay in the reply. I can't see the error you mention. Could you share a screenshot please? 

Thanks!

**Comment by mtsokol** [comment]
@osanseviero Hi! I just checked git blame and it's been fixed month ago:
https://github.com/tensorflow/graphics/commit/9753b691d4704354cef2b0273f10a5324894d63e

**Comment by osanseviero** [comment]
Thanks for pointing this out!
