### ISSUE TITLE
not able to view mesh custom dataset

### ISSUE THREAD

**Issue by mahaling** [tensorflow/graphics#532]
I am trying to create my own dataset of neuro organelles and created the tfrecords based on solutions posted here in the repo. 
I am trying to view them through the mesh viewer (not through jupyter locally, but through colab notebook by uploading the tfrecords to google drive.). I am unable to view any of the meshes and I am getting only a black screen. 
I have two classes in my mesh (0 and 1). I can upload the tfrecord somewhere and share it here (if I know how). 

Has anyone tried viewing their meshes using colab notebook?
Any help is appreciated. Thanks!

**Comment by mahaling** [comment]
I custom wrote the viewer class and made it work for my dataset.

**Comment by IvanGarcia7** [comment]
@mahaling could you share the code? I have the same problem
