### ISSUE TITLE
Tensorflow.js for the web browser with Tensorflow Graphics

### ISSUE THREAD

**Issue by kavikode** [tensorflow/graphics#54]
We'd like to include Tensorflow Graphics for the web browser using Tensorflow.js.

Can you please let us know the steps we can take to make this possible?

**Comment by julienvalentin** [comment]
I do not have any experience with Tensorflow.js and hence will not be able to answer your question.

**Comment by kavikode** [comment]
Thank you!

**Comment by podlipensky** [comment]
We haven't explored Tensorflow.js yet, feel free to create PR if you think it can be valuable for others.
