### ISSUE TITLE
name '_publish' is not defined

### ISSUE THREAD

**Issue by XuankeShi** [tensorflow/graphics#56]
When I run the mesh_segmentation demo in the jupyter notebook,it always occurs this problem,I  don't know  how to solve it ,  looking forward to yout reply,  I use  tensorflow-gpu-1.4.0  python3.7  cuda10.0 

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-7-0049de5dbd79> in <module>
     19     'vertex_colors': mesh_viewer.SEGMENTATION_COLORMAP[test_labels[0, ...]],
     20 }
---> 21 input_viewer = mesh_viewer.Viewer(input_mesh_data)

~/anaconda3/envs/tf-graphics/lib/python3.7/site-packages/tensorflow_graphics/notebooks/mesh_viewer.py in __init__(self, source_mesh_data)
     56 
     57   def __init__(self, source_mesh_data):
---> 58     context = threejs_visualization.build_context()
     59     self.context = context
     60     light1 = context.THREE.PointLight.new_object(0x808080)

~/anaconda3/envs/tf-graphics/lib/python3.7/site-packages/tensorflow_graphics/notebooks/threejs_visualization.py in build_context()
     72   """Builds a javascript context."""
     73   threejs_url = 'https://www.gstatic.com/external_hosted/threejs-r98/'
---> 74   _publish.javascript(url=threejs_url + 'three.min.js')
     75   _publish.javascript(url=threejs_url + 'examples/js/controls/OrbitControls.js')
     76   return _js_builder.Js(mode=_js_builder.PERSISTENT)

NameError: name '_publish' is not defined

and there is a warning :
WARNING: Logging before flag parsing goes to stderr.
W0726 19:06:15.274680 140164554278656 module_wrapper.py:136] From /home/shixuanke/anaconda3/envs/tf-graphics/lib/python3.7/site-packages/tensorflow_core/python/util/module_wrapper.py:163: The name tf.estimator.inputs is deprecated. Please use tf.compat.v1.estimator.inputs instead.

Warning: To use the threejs_vizualization, please install the colabtools package following the instructions detailed in the README at github.com/tensorflow/graphics.
W0726 19:06:30.580069 140164554278656 module_wrapper.py:136] From /home/shixuanke/anaconda3/envs/tf-graphics/lib/python3.7/site-packages/tensorflow_core/python/util/module_wrapper.py:163: The name tf.enable_eager_execution is deprecated. Please use tf.compat.v1.enable_eager_execution instead

**Comment by julienvalentin** [comment]
The viewer based on ThreeJS is unfortunately only compatible with Colab (ie not Jupyter). @podlipensky is looking into upgrading the visualization used in the demos to run in Jupyter. He should be able to give an update on this front.

**Comment by podlipensky** [comment]
I'll update the ticket when we add Jupyter support.

**Comment by julienvalentin** [comment]
Given the current scope, I think it is fair to assume that we will focus on Colab. We would nevertheless be more than happy to have a discussion regarding Jupyter support if this is something you want to develop.

**Comment by uestcjackey** [comment]
@podlipensky  Hi, have you done this for add Jupyter support or other plot ways just like pytorch did
