### ISSUE TITLE
inverse_rendering.ipynb does not work on google colab

### ISSUE THREAD

**Issue by gengdai** [tensorflow/graphics#650]
Hi 

I tried the notebook example of inverse_rendering on colab, but when the optimization starts, I got the following error:

ImportError                               Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/tensorflow_graphics/rendering/opengl/rasterization_backend.py in <module>()
     25 try:
---> 26   from tensorflow_graphics.rendering.opengl import gen_rasterizer_op as render_ops
     27 except ImportError:

ImportError: cannot import name 'gen_rasterizer_op' from 'tensorflow_graphics.rendering.opengl' (/usr/local/lib/python3.7/dist-packages/tensorflow_graphics/rendering/opengl/__init__.py)

During handling of the above exception, another exception occurred:

NotFoundError                             Traceback (most recent call last)
13 frames
<ipython-input-23-fc9fad4ded1c> in <module>()
      9 
     10 learning_rate = 0.02 #@param {type: "slider", min: 0.002, max: 0.05, step: 0.002}
---> 11 start = render_forward(variables, rasterization_func)
     12 optimizer = tf.keras.optimizers.Adam(learning_rate)
     13 animation_images = [start.numpy()]

<ipython-input-20-d99d115cd26c> in render_forward(variables, rasterization_func)
     73 
     74   rendered = rasterization_func(projection, image_width, image_height,
---> 75                                 variables['light_direction'])
     76 
     77   background_rgba = variables['background_color']

<ipython-input-20-d99d115cd26c> in rasterize_without_splatting(projection, image_width, image_height, light_direction)
     36       'uv': uv_coords,
     37       'normals': normals
---> 38   }, projection, (image_height, image_width))
     39 
     40   lit = shade(rasterized, light_direction)

/usr/local/lib/python3.7/dist-packages/tensorflow_graphics/rendering/triangle_rasterizer.py in rasterize(vertices, triangles, attributes, view_projection_matrix, image_size, enable_cull_face, backend, name)
    110         image_size_backend,
    111         enable_cull_face=enable_cull_face,
--> 112         backend=backend)
    113 
    114     rasterized = rasterized.layer(0)

/usr/local/lib/python3.7/dist-packages/tensorflow_graphics/rendering/rasterization_backend.py in rasterize(vertices, triangles, view_projection_matrices, image_size, enable_cull_face, num_layers, backend)
     79   elif backend == RasterizationBackends.OPENGL:
     80     backend_module = importlib.import_module(
---> 81         "tensorflow_graphics.rendering.opengl.rasterization_backend")
     82   else:
     83     raise KeyError("Backend is not supported: %s." % backend)

/usr/lib/python3.7/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

/usr/lib/python3.7/importlib/_bootstrap.py in _gcd_import(name, package, level)

/usr/lib/python3.7/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.7/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/lib/python3.7/importlib/_bootstrap.py in _load_unlocked(spec)

/usr/lib/python3.7/importlib/_bootstrap_external.py in exec_module(self, module)

/usr/lib/python3.7/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

/usr/local/lib/python3.7/dist-packages/tensorflow_graphics/rendering/opengl/rasterization_backend.py in <module>()
     28   import os
     29   dir_path = os.path.dirname(os.path.abspath(__file__))
---> 30   render_ops = tf.load_op_library(os.path.join(dir_path, "rasterizer_op.so"))
     31 # pylint: enable=g-import-not-at-top
     32 

/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/load_library.py in load_op_library(library_filename)
     56     RuntimeError: when unable to load the library or get the python wrappers.
     57   """
---> 58   lib_handle = py_tf.TF_LoadLibrary(library_filename)
     59   try:
     60     wrappers = _pywrap_python_op_gen.GetPythonWrappers(

NotFoundError: /usr/local/lib/python3.7/dist-packages/tensorflow_graphics/rendering/opengl/rasterizer_op.so: undefined symbol: _ZN4absl14lts_2020_09_238AlphaNumC1ENS0_3HexE

I got the same error when I run the notebook on my local ubuntu laptop with cpu-only tensorflow backend. It seems that there is something wrong with the rasterizer. Can anyone help me with this issue? Thank you so much.

**Comment by naufalso** [comment]
I tried to run the notebook using collab for CPU and GPU, but it still does not work (season crashed / runtime restarted when running run optimization cell).

What should the exact version for TF, TF AddOns, and tensorflow_graphics  to run this notebook?


Thank you

**Comment by fcole** [comment]
I've pushed a change that uses a sampling op for texture_map that uses only pure-TF ops, and updated the tensorflow_graphics pypi package. For me now the Colab runs successfully in CPU and GPU mode and it should be more robust to version mismatches in the future. I will close this issue now but please reopen if you continue to have problems.

**Comment by jlartois** [comment]
The inverse_rendering.ipynb is not working on google colab, neither in a CPU or GPU runtime. Could someone help me solve the following error? I appreciate any pointers, as this is a rather neat example notebook.

```NotFoundError                             Traceback (most recent call last)

[<ipython-input-11-eb040ff4d63b>](https://localhost:8080/#) in <cell line: 11>()
      9 
     10 learning_rate = 0.02 #@param {type: "slider", min: 0.002, max: 0.05, step: 0.002}
---> 11 start = render_forward(variables, rasterization_func)
     12 optimizer = tf.keras.optimizers.Adam(learning_rate)
     13 animation_images = [start.numpy()]

[<ipython-input-8-d99d115cd26c>](https://localhost:8080/#) in render_forward(variables, rasterization_func)
     72                          tf.matmul(look_at_4x4, model_rotation_4x4))
     73 
---> 74   rendered = rasterization_func(projection, image_width, image_height,
     75                                 variables['light_direction'])
     76 

[<ipython-input-8-d99d115cd26c>](https://localhost:8080/#) in rasterize_then_splat(projection, image_width, image_height, light_direction)
     44 def rasterize_then_splat(projection, image_width, image_height,
     45                          light_direction):
---> 46   return splat.rasterize_then_splat(vertices, triangles, {
     47       'uv': uv_coords,
     48       'normals': normals

[/usr/local/lib/python3.10/dist-packages/tensorflow_graphics/rendering/splat.py](https://localhost:8080/#) in rasterize_then_splat(vertices, triangles, attributes, view_projection_matrix, image_size, shading_function, num_layers, return_extra_buffers, backend, name)
    265     # Back face culling is necessary when rendering multiple layers so that
    266     # back faces aren't counted as occluding layers.
--> 267     rasterized = rasterization_backend.rasterize(
    268         vertices,
    269         triangles,

[/usr/local/lib/python3.10/dist-packages/tensorflow_graphics/rendering/rasterization_backend.py](https://localhost:8080/#) in rasterize(vertices, triangles, view_projection_matrices, image_size, enable_cull_face, num_layers, backend)
     74   """
     75   if backend == RasterizationBackends.CPU:
---> 76     backend_module = importlib.import_module(
     77         "tensorflow_graphics.rendering.kernels.rasterization_backend")
     78   elif backend == RasterizationBackends.OPENGL:

[/usr/lib/python3.10/importlib/__init__.py](https://localhost:8080/#) in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

/usr/lib/python3.10/importlib/_bootstrap.py in _gcd_import(name, package, level)

/usr/lib/python3.10/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.10/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/lib/python3.10/importlib/_bootstrap.py in _load_unlocked(spec)

/usr/lib/python3.10/importlib/_bootstrap_external.py in exec_module(self, module)

/usr/lib/python3.10/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

[/usr/local/lib/python3.10/dist-packages/tensorflow_graphics/rendering/kernels/rasterization_backend.py](https://localhost:8080/#) in <module>
     35   import os
     36   dir_path = os.path.dirname(os.path.abspath(__file__))
---> 37   render_ops = tf.load_op_library(os.path.join(dir_path, "rasterizer_op.so"))
     38 # pylint: enable=g-import-not-at-top
     39 

[/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/load_library.py](https://localhost:8080/#) in load_op_library(library_filename)
     52     RuntimeError: when unable to load the library or get the python wrappers.
     53   """
---> 54   lib_handle = py_tf.TF_LoadLibrary(library_filename)
     55   try:
     56     wrappers = _pywrap_python_op_gen.GetPythonWrappers(

NotFoundError: /usr/local/lib/python3.10/dist-packages/tensorflow_graphics/rendering/kernels/rasterizer_op.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb```
