### ISSUE TITLE
CVX-Net Pretrained model release

### ISSUE THREAD

**Issue by chpark1111** [tensorflow/graphics#697]
Hi!
Thanks for your wonderful work!

I'm curious when you guys will release the pre-trained models!

I'm doing a research related to such topic and I'll really appreciate if you can release the pre-trained models!

**Comment by Awcrr** [comment]
Hi Chanhyeok,

I'm Boyang, one of the authors of CvxNet.

The biggest problem with releasing the pre-trained models is the license constraint of ShapeNet Data and its derivatives, in our case the models trained on ShapeNet.

Another way we can help you is that if you have specific examples in shapenet that you want to show the cvxnet results in your paper, we can send you those, only for academic purpose. Please email me if you need that.

Cheers,
Boyang

**Comment by chpark1111** [comment]
Thanks for the fast respond! 
I'll send you those emails when we need it!

Sincerely,
Chanhyeok

**Comment by Awcrr** [comment]
> 

You can find my email on my [webpage](https://boyangdeng.com/).

Can you please close this issue for now?
