### ISSUE TITLE
Version issue about tensorboard graphics

### ISSUE THREAD

**Issue by betairylia** [tensorflow/graphics#8]
Sorry for this question. Could you clarify the installation steps and versions to use the tensorboard extension with mesh and point clouds?

I installed tf-nightly and tb-nightly with anaconda3, python 3.6.7, cuda10.0, Ubuntu 18.04.
However, the compiled webfiles.zip in tensorboard root seems different from the html and js files in this repo. If I use installed tb-nightly to render point clouds, the result image is some green big dots (very big). In precise the size of points is 1.0 (default value) instead of 0.005 in this repo, and colors are fixed as #00FF00 instead of run color or per-point color in this repo. Also some errors could happen, and if it happens I can no longer view visualization results in tensorboard. How should I install the correct version? Thanks!

**Comment by podlipensky** [comment]
Try to install JUST tf-nightly, it should contain proper version of tb-nightly

**Comment by julienvalentin** [comment]
Let us know in case you are still facing problems!

Best.

**Comment by betairylia** [comment]
Thanks for your reply!
Unfortunately I have some problems with tf-nightly (I am using some custom ops that will throw segfault in tf-nightly version, but runs properly with tf 1.13). Is it even possible to use tensorboard 3D with tensorflow 1.13 ?

Also I have checked the corresponding webfiles.zip (under tensorboard/) after installed tf-nightly. index.html contains:
`b.prototype._createPointCloud=function(a,b){a=a.vertices;b=this._applyDefaults(b,{material:{cls:"PointsMaterial",color:65280}});`
which seems to be exactly same as before, without size=0.005, and the color was fixed as 65280(#00ff00). Am I doing something wrong?

BTW the version installed tb-nightly versions are the same for `pip install tf-nightly` and `pip install tb-nightly`. They are `tb-nightly-1.14.0a20190515` at current time.

**Comment by podlipensky** [comment]
The plugin is not part of current version of TensorBoard, but should work fine with TF 1.13 if you manage to install/register the plugin in your local TensorBoard version. Default point size will be fixed soon, meantime try to just pass material threejs-compatible config, i.e.:

```
config_dict = {
  'cls': 'PointsMaterial',
  'size': 0.005,
}
...
mesh_summary.op('point_cloud_tensor', vertices=vertices_tensor, config_dict=config_dict)
```

**Comment by betairylia** [comment]
Thanks!
