### ISSUE TITLE
Is the aim of Tensorflow Graphics to implement 3D reconstruction methods, or is it just a collection of tools?

### ISSUE THREAD

**Issue by jimbojetlag** [tensorflow/graphics#9]
The impression I got from your presentation was that this is a library that implements 3D reconstruction from 2D image approaches. But after looking at the source code, and some future features in readme, it seems like this is going to be a collection of tools.

Could you clarify the roadmap for the library? If you are indeed going to implement 3D reconstruction methods, given that this field is still open to research with no de facto solution, which approaches are you going to implement? Any timelines?

**Comment by julienvalentin** [comment]
I guess that here you are talking about machine learning techniques / deep networks to infer 3D from 2D. Right now we don't have anything in the pipeline in that direction for TensorFlow Graphics. Nevertheless, this is something we discussed internally and we are open to contributions.

In general the main aim with TensorFlow Graphics is not to be a collection of networks, but rather to be a library that provides researchers and developers with computer graphics layers and 3D data. 

Best.
